.extravote{margin:0
0 10px}.extravote-small{}.extravote-stars,.extravote-info{margin:0!important;padding:0!important;position:relative;vertical-align:middle}.extravote-info.ihide{display:none}.voted .extravote-info.ihide,.extravote-stars{display:inline-block}.extravote-stars,
.extravote-star a,
.extravote-info,
.extravote-stars .current-rating{height:25px;line-height:25px}.size-2 .extravote-stars,
.size-2 .extravote-star a,
.size-2 .extravote-info,
.size-2 .extravote-stars .current-rating ,
.extravote-small .extravote-stars,
.extravote-small .extravote-star a,
.extravote-small .extravote-info,
.extravote-small .extravote-stars .current-rating{height:22px;line-height:22px}.size-3 .extravote-stars,
.size-3 .extravote-star a,
.size-3 .extravote-info,
.size-3 .extravote-stars .current-rating ,
.size-2.extravote-small .extravote-stars,
.size-2.extravote-small .extravote-star a,
.size-2.extravote-small .extravote-info,
.size-2.extravote-small .extravote-stars .current-rating{height:19px;line-height:19px}.size-3.extravote-small .extravote-stars,
.size-3.extravote-small .extravote-star a,
.size-3.extravote-small .extravote-info,
.size-3.extravote-small .extravote-stars .current-rating{height:16px;line-height:16px}.extravote-stars{font-size:1em;overflow:hidden;width:125px}.size-2 .extravote-stars,
.extravote-small .extravote-stars{width:110px}.size-3 .extravote-stars,
.size-2.extravote-small .extravote-stars{width:95px}.size-3.extravote-small .extravote-stars{width:80px}.extravote-info{font-size: .78em}.extravote-star{background-position:0!important;background-image:none;display:inline;margin:0!important;padding:0!important}.extravote-stars,
.extravote-star a:hover,
.extravote-stars .current-rating{background-image:url("/plugins/content/extravote/assets/images/star.png")!important;background-color:transparent!important;background-repeat:repeat-x!important}.size-2 .extravote-stars,
.size-2 .extravote-star a:hover,
.size-2 .extravote-stars .current-rating,
.extravote-small .extravote-stars,
.extravote-small .extravote-star a:hover,
.extravote-small .extravote-stars .current-rating{background-image:url("/plugins/content/extravote/assets/images/star-2.png")!important}.size-3 .extravote-stars,
.size-3 .extravote-star a:hover,
.size-3 .extravote-stars .current-rating,
.size-2.extravote-small .extravote-stars,
.size-2.extravote-small .extravote-star a:hover,
.size-2.extravote-small .extravote-stars .current-rating{background-image:url("/plugins/content/extravote/assets/images/star-3.png")!important}.size-3.extravote-small .extravote-stars,
.size-3.extravote-small .extravote-star a:hover,
.size-3.extravote-small .extravote-stars .current-rating{background-image:url("/plugins/content/extravote/assets/images/star-4.png")!important}.extravote-star a:hover,
.extravote-stars .current-rating{background-position:left -1000px}.extravote-star a,
.extravote-stars .current-rating{border:medium none;cursor:pointer;left:0;outline:none;overflow:hidden;position:absolute;text-indent:-1000em!important;top:0}.extravote-star a:hover{background-position:left bottom!important}.extravote-star a:focus,
.extravote-star a:active{background:none!important}.extravote-stars .current-rating{background-position:left center;z-index:1}.extravote-star a.ev-5-stars,
.extravote-star a.ev-10-stars,
.extravote-star a.ev-15-stars,
.extravote-star a.ev-20-stars,
.extravote-star a.ev-25-stars,
.extravote-star a.ev-30-stars,
.extravote-star a.ev-35-stars,
.extravote-star a.ev-40-stars,
.extravote-star a.ev-45-stars,
.extravote-star a.ev-50-stars{margin:0;padding:0}.extravote-star a.ev-5-stars{width:10%;z-index:12}.extravote-star a.ev-10-stars{width:20%;z-index:11}.extravote-star a.ev-15-stars{width:30%;z-index:10}.extravote-star a.ev-20-stars{width:40%;z-index:9}.extravote-star a.ev-25-stars{width:50%;z-index:8}.extravote-star a.ev-30-stars{width:60%;z-index:7}.extravote-star a.ev-35-stars{width:70%;z-index:6}.extravote-star a.ev-40-stars{width:80%;z-index:5}.extravote-star a.ev-45-stars{width:90%;z-index:4}.extravote-star a.ev-50-stars{width:100%;z-index:3}